// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/telemetry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkTelemetry_Subscribe_FullMethodName = "/NetworkTelemetry/Subscribe"
)

// NetworkTelemetryClient is the client API for NetworkTelemetry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Always returns stream, but:
// STREAM mode → continuous updates
// ONCE mode → single message then closes stream
type NetworkTelemetryClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
}

type networkTelemetryClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkTelemetryClient(cc grpc.ClientConnInterface) NetworkTelemetryClient {
	return &networkTelemetryClient{cc}
}

func (c *networkTelemetryClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkTelemetry_ServiceDesc.Streams[0], NetworkTelemetry_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkTelemetry_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

// NetworkTelemetryServer is the server API for NetworkTelemetry service.
// All implementations must embed UnimplementedNetworkTelemetryServer
// for forward compatibility.
//
// Always returns stream, but:
// STREAM mode → continuous updates
// ONCE mode → single message then closes stream
type NetworkTelemetryServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	mustEmbedUnimplementedNetworkTelemetryServer()
}

// UnimplementedNetworkTelemetryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkTelemetryServer struct{}

func (UnimplementedNetworkTelemetryServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedNetworkTelemetryServer) mustEmbedUnimplementedNetworkTelemetryServer() {}
func (UnimplementedNetworkTelemetryServer) testEmbeddedByValue()                          {}

// UnsafeNetworkTelemetryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkTelemetryServer will
// result in compilation errors.
type UnsafeNetworkTelemetryServer interface {
	mustEmbedUnimplementedNetworkTelemetryServer()
}

func RegisterNetworkTelemetryServer(s grpc.ServiceRegistrar, srv NetworkTelemetryServer) {
	// If the following call pancis, it indicates UnimplementedNetworkTelemetryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkTelemetry_ServiceDesc, srv)
}

func _NetworkTelemetry_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetworkTelemetryServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkTelemetry_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

// NetworkTelemetry_ServiceDesc is the grpc.ServiceDesc for NetworkTelemetry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkTelemetry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NetworkTelemetry",
	HandlerType: (*NetworkTelemetryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _NetworkTelemetry_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/telemetry.proto",
}
